application: jorgeavilasuarez
version: cms
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /fonts/(.*\.(woff))$
  static_files: fonts/\1
  upload: fonts/.*\.(woff)$
  http_headers:
    Content-Type: application/woff
  
- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /product.*
  script: modules.stock.main.app
  login: required
  
- url: /images.*
  script: modules.images.main.app
  login: required

- url: /upload.*
  script: utils.upload.app
  login: required 

- url: .*
  script: main.app
  login: required 

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"